### ISSUE TITLE
Change versioning scheme

### ISSUE THREAD

**Issue by rickstaa** [WyriHaximus/github-action-get-previous-tag#10]
First of all thanks a lot for the great action. Please allow me to throw in one suggestion. Maybe it is an idea to change the versioning scheme to include the v prefix? I think this is the convention used by official GitHub actions like the [actions/checkout](https://github.com/actions/checkout) action. This will prevent confusion when users like me try to use the package based on a specific version:

```yml
- name: 'Get Previous tag'
  id: previous_tag
  uses: WyriHaximus/github-action-get-previous-tag@v1
```

Haya14busa provided a very handy action to make sure the major version tag points to the newest release. You can find it [here](https://github.com/haya14busa/action-update-semver).

related to #9
