### ISSUE TITLE
Allow defining a default tag

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [WyriHaximus/github-action-get-previous-tag#18]
I'm using your action in a template-repo, and when somebody uses the template, the first CI run will fail with
```
Could not find any tags because: 
fatal: No names found, cannot describe anything.
```

Your action is correct. There are no tags, it's a new repo :D 
The obvious workaround is to create a tag, e.g., 0.0.1.

However, I would like to propose that we can specify a default tag, e.g., 0.0.1, like this:
```
      - name: 'Get Previous tag'
        id: get_previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.0.1"
        with:
          defaultTag: "0.0.1"
      - name: 'Get next patch version'
        id: get_next_semver_tag
        uses: "WyriHaximus/github-action-next-semvers@v1.1"
        with:
          version: ${{ steps.get_previous_tag.outputs.tag }}
```

This would require a code change here:
https://github.com/WyriHaximus/github-action-get-previous-tag/blob/3f018b4126e1d6652bcb11a64cb505e341b70c2d/main.js#L11-L16

To respond with
```
            console.log(`::set-output name=tag::${tag}`);
            console.log(`::set-output name=timestamp::${timestamp}`);
```
instead of 
```
            process.exit(1);
```

if a default tag is set. The timestamp, in this case, could just be set to the current time.
