### ISSUE TITLE
Not seeing latest tag

### ISSUE THREAD

**Issue by petehannam** [WyriHaximus/github-action-get-previous-tag#24]
I've been having a few problems with this plugin over the past couple of days - unsure if it's the plugin or Github but it's not resolving the latest tag (it's been working fine for _months_ before this week).

The action is resolving 1.161.0:
![screenshot-github com-2021 06 03-11_53_52](https://user-images.githubusercontent.com/2697993/120634078-c40da600-c462-11eb-953c-05b31ecedd69.png)

But the latest is actually 1.162.0:
![screenshot-github com-2021 06 03-11_54_16](https://user-images.githubusercontent.com/2697993/120634031-b8ba7a80-c462-11eb-8e98-6fdbd62eafc4.png)

This isn't a time issue as reported in a previous issue, as 1.162.0 was created yesterday.

My script is as follows (the repo is private):

```      
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
```
