### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by katelynienaber** [WyriHaximus/github-action-get-previous-tag#26]
Hello, I am trying to use this action to get the latest release tag.

The repo is here: https://github.com/zowe/vscode-extension-for-zowe/tags

As you can see, there are a lot of tags.

But the action fails with this error:
![image](https://user-images.githubusercontent.com/58596139/130909639-7830cd23-4b77-4c0d-89d0-29614611cba0.png)

I am using the action as follows:
```
      - name: Get most recent GitHub release version (2)
        id: get_gh_version_2
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
```

**Comment by AustinSanders** [comment]
@katelynienaber Are you including fetch depth 0 in your checkout action? i.e.:

```
    steps:
    - name: checkout
      uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: get_latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
```
