### ISSUE TITLE
git not found?

### ISSUE THREAD

**Issue by cristianmtr** [WyriHaximus/github-action-get-previous-tag#27]
```
Run WyriHaximus/github-action-get-previous-tag@v1
/usr/bin/docker exec  d177be54cbfdf6e6b4ae294e4f83da6da9b144df31cf1485904d55c896c89c7e sh -c "cat /etc/*release | grep ^ID"
Could not find any revisions because: 
/bin/sh: 1: git: not found
```

Shouldn't this action install `git`? I also use the checkout action before yours, which also relies on git. What am I doing wrong? My config is :

```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: ""
```
